apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: default
  labels:
    app: ecommerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
        - name: ecommerce-monolith
          image: woorea/ecommerce-frontend:latest
          ports:
            - containerPort: 80
              name: http
