apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host }}`)
      kind: Rule
      services:
        - name: {{ include "helm.fullname" $ }}
          port: 80
    {{- end }}
